### ISSUE TITLE
InRelease repository is unsigned?

### ISSUE THREAD

**Issue by ttriche** [eddelbuettel/r2u#2]
```
Error: The repository 'http://ppa.launchpad.net/edd/misc/ubuntu jammy InRelease' is not signed.
Warning: GPG error: http://ppa.launchpad.net/edd/misc/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 67C2D66C4B1D4339
```

**Comment by ttriche** [comment]
this fixed it: 
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 67C2D66C4B1D4339
```

**Comment by eddelbuettel** [comment]
The README.md (and its copy in the documentation website) as well as the setup scripts detail how to get a key.  The command you show is valid, but no longer recommended and 22.04 will in fact whine, hence my switch using keys via `wget` and `tee` into `.asc` files.

I would be all ears about suggestions to make the documentation more clear on this. 

I hope you are finding `r2u` otherwise useful.

**Comment by ttriche** [comment]
I followed the directions in the README. This additional step was nevertheless required. R2U itself is working fantastically well and is quite fast. I am loving it v

**Comment by eddelbuettel** [comment]
Ok, I may have tunnel vision here as I looked at it myself but can you suggest a diff to the README.md that would make the need for a key more obvious than sections 'First add a repo key' and 'Second add the repo to apt' ?

Otherwise, glad you're liking.  It seems to work as planned so far ...

**Comment by ttriche** [comment]
I mean I’ve been using apt and GPG keys for 10 years, Unix and Linux for 25, so when I repeatedly got the same error after adding the keys, I just googled the error string to find a solution that securely matched up the public key with the one used for signing the repo. I’ll see if I can find a more straightforward and/or Ubuntu-recommended approach that works the same in a fresh 22.04 container. 

Meanwhile, thanks for making my R-4.2.0 upgrade radically faster. What used to take a full day (upgrading old packages) took minutes with r2u. 🎉

**Comment by eddelbuettel** [comment]
> I mean I’ve been using apt and GPG keys for 10 years, Unix and Linux for 25, so when I repeatedly got the same error after adding the keys, I just googled the error string to find a solution that securely matched up the public key with the one used for signing the repo. I’ll see if I can find a more straightforward and/or Ubuntu-recommended approach that works the same in a fresh 22.04 container.

Can you please try again so that we can iron this out?   There are only two repos, and two keys (but now two methods for 20.04 and 22.04) and we should shake this out.  You error report is not really fully complete -- you quote the error message but I do not know _how_ you set things up.  I tested both setup scripts on "empty" (container) systems, they worked for me.

And yes I have the same 25 years and really wanted a full `apt` repo too :)

(But I didn't blow my `/usr/local/lib/R/site-library` away for 4.1 nor did I for 4.2,  Technically, these didn't require full rebuild (as the NEWS file from R upstream confirms--only for some graphics device packages).

Anyway, it's all good so please help me spread the word about this.

**Comment by ttriche** [comment]
I'll take a whack at this (above) when I build a new Docker image for our HPC installs.  I'm tired of CentOS docker images that are rapidly out of date, and with this working properly, why not have trainees just use r2u and be done with it...

**Comment by eddelbuettel** [comment]
Right on.  And FWIW I have long provided such containers as variants of the basic rocker container.  One for Ubuntu that had c2d4u, one top of that one with `bspm` support, now the same with `r2u`.  Should be easy for to customize with additional / preferred apps as you need it.  The Dockerfiles for `r2u` are in its repo, the other one are in the Rocker repos.

**Comment by mmk00188** [comment]
I installed the R studio and r2u according to your direction in README.md, few months ago and it works perfectly, but recently i receive the following message when i try to install a new packages 
Err http;//dl.google.com/linux/chrome/deb stable InRelease 
  The following signature couldn't be verified because the public key is not available : NO_PUBKEY 32EE5355A6BC6E42
i would be appreciated if you could help me to fix this problem

**Comment by eddelbuettel** [comment]
And old (and now deprecated) form of importing a particular is

```sh
sudo apt-key adv --recv-keys 32EE5355A6BC6E42 
```

which you could try.

**Comment by mmk00188** [comment]
thank you so much, it works for me 
you made my day and i don't know how to thank you

**Comment by eddelbuettel** [comment]
Just play it forward.  We all do. We all have been helped at some point, and so we keep pushing the same can ...
