### ISSUE TITLE
ETA on switch to BioC 3.16

### ISSUE THREAD

**Issue by PeteHaitch** [eddelbuettel/r2u#21]
Hi Dirk,

BioC 3.16 is hot off the presses (https://bioconductor.org/news/bioc_3_16_release/).
Will coverage of BioC by **r2u** switch or extend to BioC 3.16?
I've no idea what's involved in making such a change, but, if feasible, do you have an ETA?

Thanks,
Pete

**Comment by eddelbuettel** [comment]
It's a good question. I have been pondering it myself for a while with 3.16 on the horizon.

r2u lives and dies by what rspm gives it, and compiles as needed.  For BioC, we always compiled.  So that is some 200+ packages.  Not insurmountable, but some work.  I was [reminder](https://community-bioc.slack.com/archives/CLUJWDQF4/p1650295541134819?thread_ts=1650293758.406059&cid=CLUJWDQF4)  how to compute dependency depth. So what we need now, I think, is a simple routine that
- loops over all BioC packages in the r2u universe
- computes their 'full' dependency length 
- loops over these from the inside out:
  - dependency count 0 (BiocManager likely?)
  - dependency count 1
  - ....
  - dependency count N (for whatever value of N)
  
Which seems feasible.  So ... can you help?   I am still a wee bit tied up as it is a teaching term for me.

**Comment by PeteHaitch** [comment]
> So ... can you help? I am still a wee bit tied up as it is a teaching term for me.

Not immediately, unfortunately.
Next week I'm examining Masters theses and doing final organisation of BioC Asia for end of the month.
I can try to return to it in ~2 weeks and see where I can get with it

**Comment by eddelbuettel** [comment]
A few days ago I noodled around with the package dependency 'graph' and worked out a way to script this.  With some time today I ran it for 'jammy' aka 22.04 -- and the BioConductor packages included in that half of `r2u` have now been rebuilt for BioConductor 3.16.  And I just started 'focal' aka 20.04 for completeness.

**Comment by eddelbuettel** [comment]
This is now complete.

**Comment by PeteHaitch** [comment]
Amazing, thanks Dirk!

**Comment by eddelbuettel** [comment]
Let me know if you find particular (popular) packages missing.  The BioC side is more manual than the CRAN side so I do not think I can get to full coverage (== venue for volunteers to shine ...) but I could add a few if it made sense.  What we have now is determined strictly by what CRAN pulls is -- so a wee bit random.
