### ISSUE TITLE
Provide a sample GitHub actions setup

### ISSUE THREAD

**Issue by henrykironde** [eddelbuettel/r2u#33]
I have tried this tool, but currently the setup fails to use the installed packages.
Any help would be appreciated.

**Comment by eddelbuettel** [comment]
Please see for example [r-ci.sh](https://eddelbuettel.github.io/r-ci/) (which I use for almost all my GitHub projects) or else follow the scripts.  _It is just regular Ubuntu_ so you can also `apt install` as you see fit, or use `bspm` so that `remotes::install_deps()` takes over (`r-ci` does that or ...)

Providing CI is outside of the scope of r2u: it is just a repository. You can deploy it as you see fit.

Lastly, please take a moment to re-read your paragraph above. It is missing _any_ relevant tangible information. You did detail what you did, nor what result you expected, nor the result you got.
