### ISSUE TITLE
Uninstall/removal instructions

### ISSUE THREAD

**Issue by Alanocallaghan** [eddelbuettel/r2u#35]
Hey, this works well generally, but I ran into some problems on a laptop that I couldn't really be bothered debugging. I think I got through the removal process semi-okay by trial and error but it would be good to have some explicit ones.

The steps I followed were:

1. `remove.packages("bspm")` or the system package `r-cran-bspm`
2. remove the bspm package folder from your library if 1. is not successful
3. remove `bspm::enable()` from your `Rprofile.site`
4. Remove the cran_apt listings from your sources, eg by `rm /etc/apt/sources.list.d/cran_apt.list`

**Comment by eddelbuettel** [comment]
Sure. It's an apt repo.  So you must remove the listing.

Sorry you were unable to debug.  Nobody is helped by that.

**Comment by Alanocallaghan** [comment]
I mean it took me a while of trying to figure out why removing bspm and the apt listing wouldn't work, and I figured somebody with less of an idea where to look would be helped by some basic removal instructions, but I guess you're totally within your rights to be extremely curt and ignore this. Thanks anyways

**Comment by quirinmanz** [comment]
Hi,
First of all, thank you :)
I set up r2u a while ago on my local laptop and haven't used it much because I was working on a remote server a lot.
Now installing some packages does not work and the output is not the same as normally with `install.packages`. This gives me a hard time debugging. I wanted to remove r2u completely to see where I might have gone into a wrong direction, but following the steps above or the setup steps (backwards and removing instead of adding) does not help.
I am not too familiar with apt and system installations, so in this case some simple instructions on how to revert R to use the old way of installing would be great.
Best,
Quirin

**Comment by alanocallaghan** [comment]
Without wishing to be rude and revisiting this far later,

>  Driving by and asking 'yo would be good to have docs' doesn't make it so either.

I didn't do that. I posted the steps that I needed to do to fix my broken system because I thought it might be useful for other people. I was more than willing to contribute some docs if you thought that was useful (evidently not based on your reply?). If you had suggested this, and I had then said "No thanks, I cba" then sure, your complaints would be well-warranted. But that's not how it went down. You effectively told me to sod off immediately, and then complained about having limited resources.

There's really not any need to be this dismissive and I have noticed it's quite common for you to act this way on various platforms. I suggest you should use an issue template to pre-empt such conversations, as it may reduce the need for you to reply to unwanted conversations such as this.

(unsubscribing from notifications)

**Comment by eddelbuettel** [comment]
Anytime.  In essence removal just amounts to looking at the four (or five, depending how you count) steps detailed in the README (and the corresponding setup shell script for a given Ubuntu release) and undoing each of them.
