### ISSUE TITLE
can 'install.packages("bspm")' be used if bspm is not installed?

### ISSUE THREAD

**Issue by apsteinmetz** [eddelbuettel/r2u#41]
This may just be a documentation issue. In "step 5" of your setup instructions you say to run
```
Rscript -e 'install.packages("bspm")'
```
But `bpsm` is installed so the user can use `install.packages()`, right?  Catch-22? The script in "Step 5" failed for me but 
`apt install r-cran-bspm` from the console worked fine  and `install.packages()` worked thereafter so no worries.

**Comment by eddelbuettel** [comment]
> But `bpsm` is installed 

Well that depends. What exactly did you start from?  An 'empty' initial Ubuntu system?  It would not have `bspm` which is why we suggest it.

In a nutshell, `r2y` "really" works at the level of _system_ binaries.  I.e. `ggplot2` is supplied by `r-cran-ggplot2`.  Those who know their way around a Debian/Ubuntu system can get what they want via `apt` and alike.

But, and that is a big 'but' for most R users it is both easier and more convenient to use `install.packages` and *then "magically" have the packages installed as system binaries*.  That is what `bspm` does.  It translates and maps the `install.packages()` call into a system call to `apt`.  (And that is why it has to be installed by the root user.)

**Comment by eddelbuettel** [comment]
Can you talk to me like I am five years old about 
a) what Step 5 made you do
b) what error you got
c) and how you overcame it (a manual `apt install r-cran-bspm` ?)

I have run the scripts a few times by hand, and run the 'manual steps'.  But it is *always* possible that something got out of whack, and if so, I should correct it.

**Comment by eddelbuettel** [comment]
@apsteinmetz -- any follow-up?  Else happy to close if all issues are taken care of ...
