### ISSUE TITLE
Specify R version?

### ISSUE THREAD

**Issue by LukasWallrich** [eddelbuettel/r2u#74]
I now switched a lot of ci-tasks to r2u and am still very excited how fast and robust it is - so thanks again! Yet today, we ran into an issue when [an action](https://github.com/ESHackathon/CiteSource/actions/runs/11749239596/job/32735042674) required an older version of R because shinyapps.io does not support the latest version yet. Is there any way to specify the R version for r2u? Or use something like `r-lib/actions/setup-r@v2` and then switch to r2u for package installation? I'd much appreciate any guidance.

**Comment by eddelbuettel** [comment]
Good meta question, and quite appropriate for r-sig-debian because this is Debian / Ubuntu specific.

In short, within each 'stack' you get 'max(version)' over what is available. And because @marutter provides _the current_ R as a courtesy to users of all the supported Ubuntu LTS flavours (using my 'always current' R package from Debian).  That is generally also how CRAN works: assuming current R.

Now, you _can_ tell `apt` to install a given version.  In fact, that is how I write my Dockerfiles for rocker/r-base.  Quoting

https://github.com/rocker-org/rocker/blob/91be49790deb5c8a1c0f2b64ccc5fb3696645a54/r-base/4.4.2/Dockerfile#L42-L58

ie

```make
[....]
ENV R_BASE_VERSION=4.4.2


# ## During the freeze, new (source) packages are in experimental and we place the binaries in our PPA
# RUN echo "deb http://deb.debian.org/debian experimental main" > /etc/apt/sources.list.d/experimental.list \
#    && echo "deb [trusted=yes] https://eddelbuettel.github.io/ppaR400 ./" > /etc/apt/sources.list.d/edd-r4.list


## Now install R and littler, and create a link for littler in /usr/local/bin
RUN apt-get update \
        && apt-get install -y -t unstable --no-install-recommends \
                libopenblas0-pthread \
		littler \
                r-cran-docopt \
                r-cran-littler \
		r-base=${R_BASE_VERSION}-* \
		r-base-dev=${R_BASE_VERSION}-* \
                r-base-core=${R_BASE_VERSION}-* \
		r-recommended=${R_BASE_VERSION}-* \
                [...]
```
You could try to run similar commands that `apt install r-base-dev=$VER r-base-core=$VER`.  You may need to add extra flags to `apt` to force a downgrade.  It should be doable (while nonstandard) so I encourage you to experiment.

(And just to be clear I am not suggesting you use this Dockerfile or container 'as is'. r-base is Debian-based, r2u is Ubuntu based.  I am showing the above to show how `apt` _can_ follow a version constraint when the desired binary is in the `pool/` directory which is the case for us as the previous version is not deleted)

**Comment by eddelbuettel** [comment]
So no we can't.  We'd need more volunteers, more diskspace and more to-be-written code to allow current and previous versions of R.  Sorry.

**Comment by eddelbuettel** [comment]
Your best (simple) alternative is likely to use custom container.  You can start _e.g._ from r-base:4.3.3 (official R, same container as rocker/r-base:4.3.3), add the packages you need in a container build and ... store the container.  Registry at  GitHub is free, and IIRC at Docker as well 'for small scale' (unsure).  Then you can rewrite your yaml file (running _.e.g._ `ubuntu-latest` so that you can run `docker`) and simply instruct it to run in the container you name: the one you just built.  It's a nice little and something I do for example for Rcpp to have a simple matrix of R version to check against, see [here](https://github.com/RcppCore/Rcpp/blob/master/.github/workflows/ci.yaml) and note the `container: image ...` setter (you can assign a fixed string, your container).

I will try to remember that this constraint here for r2u is more or less self-imposed.  I could lift it to only rely on, say, 'R (>= 4.0.0)' but I philosophically also like to nudge use towards current R just like at CRAN.  Tradeoffs ....

**Comment by eddelbuettel** [comment]
Or if you are into 'programming with yaml' (not my favourite ...) you could rely on r2u as you do to _build_ your artifact, upload it with the workflow and ... have another job (using a suitable older R) pick it up for the deploy step satisfying the (very odd!!) constraint imposed on your there.

**Comment by LukasWallrich** [comment]
Thank you - very helpful! I built a backup action without r2u, which is very slow but probably good enough for the 2 times per year that this issue will arise ... but will pin this thread to see if we can sort it out properly.

**Comment by eddelbuettel** [comment]
I think the best 'fast' way would be run the update step from the container you with r2u under R 4.4.2 .... but invoke the update as `docker run --rm -ti rocker/r-base:4.3.3 Rscript -e 'theUpdatingRExpressionHere'` (or have `Rscript call a script ot ...).  That would get you R 4.3.3 in a 4.4.2 (or whatever) run.

Of course, I know nothing about your other needs for a deploy.  Farming it into a separate, dependent step running in the R 4.3.3 container may be easier (in terms of accessing how `shiny` deploys).  Good luck!
